[package]
name = "opi_main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
embedded-can = "0.4.1"
embedded-hal = "0.2.7"
linux-embedded-hal = "0.3.2"
socketcan = "2.0.0"
